TYPE=VIEW
query=select `temp`.`table`.`FirstName` AS `FirstName`,`temp`.`table`.`age` AS `age` from `temp`.`table`
md5=734c233f3bafd03bb9f880bd5c266d07
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-02-17 05:17:25
create-version=2
source=SELECT table.FirstName, table.age from temp.table
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `temp`.`table`.`FirstName` AS `FirstName`,`temp`.`table`.`age` AS `age` from `temp`.`table`
mariadb-version=100130
